import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseReceipt, findUserError } from '../src/lib/genlayer/receipt';
import { normalizeUint, readState, VIEW_METHODS } from '../src/lib/genlayer/state';
import { parseEnv } from '../src/config/env';
import { USER_ERROR_MESSAGES } from '../src/config/errors';
import { pollUntilAccepted, pollUntilFinalized } from '../src/lib/genlayer/poll';
import { historyReducer, type TransactionRecord } from '../src/context/transactions';
let checks = 0;
const check = (name: string, fn: () => void) => { fn(); checks++; console.log(`OK ${name}`); };
for (const statusName of ['ACCEPTED', 'FINALIZED']) check(statusName, () => assert.equal(parseReceipt({ statusName, txExecutionResultName: 'FINISHED_WITH_RETURN' }).kind, 'accepted-return'));
check('snake fields', () => assert.equal(parseReceipt({ status_name: 'ACCEPTED', tx_execution_result_name: 'FINISHED_WITH_ERROR', error: 'circuit breaker is active' }).kind, 'accepted-error'));
check('numeric maps', () => assert.equal(parseReceipt({ status: 7, txExecutionResult: 1 }).kind, 'accepted-return'));
for (const text of Object.keys(USER_ERROR_MESSAGES)) check(`UserError ${text}`, () => assert.equal(findUserError({ nested: [{ text }], bigint: 1n }), text));
for (const statusName of ['UNDETERMINED', 'VALIDATORS_TIMEOUT', 'LEADER_TIMEOUT', 'CANCELED']) check(statusName, () => assert.equal(parseReceipt({ statusName }).kind, 'no-consensus'));
for (const resultName of ['NO_MAJORITY', 'DISAGREE', 'TIMEOUT', 'DETERMINISTIC_VIOLATION', 'MAJORITY_DISAGREE']) check(resultName, () => assert.equal(parseReceipt({ resultName }).kind, 'no-consensus'));
for (const statusName of ['PENDING', 'PROPOSING', 'COMMITTING', 'REVEALING', 'READY_TO_FINALIZE', 'APPEAL_REVEALING', 'APPEAL_COMMITTING']) check(`pending ${statusName}`, () => assert.equal(parseReceipt({ statusName, txExecutionResultName: 'NOT_VOTED' }).kind, 'pending'));
check('unknown receipt', () => assert.equal(parseReceipt({}).kind, 'unknown'));
for (const value of [0, 42, 42n, 4294967295n]) check(`u32 ${value}`, () => assert.equal(normalizeUint(value, 32, 'count'), Number(value)));
for (const value of [-1, NaN, Infinity, 1.5, 4294967296n, '42']) check(`invalid u32 ${value}`, () => assert.throws(() => normalizeUint(value, 32, 'count')));
check('unsafe u64', () => assert.throws(() => normalizeUint(9007199254740992n, 64, 'ts')));
const values = ['ACTIVE', 'https://status.test', 'operational', 'https://status.test', 1n, 1700000000n, 2];
const state = await readState(async name => values[VIEW_METHODS.indexOf(name as typeof VIEW_METHODS[number])]);
check('seven-view normalization', () => assert.deepEqual(state, { ok: true, state: { status: 'ACTIVE', monitoredUrl: 'https://status.test', lastVerdict: 'operational', lastCheckedUrl: 'https://status.test', incidentCount: 1, lastCheckTimestamp: 1700000000, guardedActionCount: 2 } }));
const failure = await readState(async () => { throw new Error('RPC unavailable'); });
check('explicit read error', () => assert.deepEqual(failure, { ok: false, error: 'RPC unavailable' }));
check('safe env defaults', () => assert.equal(parseEnv({}).publicBaseUrl, ''));
for (const env of [{ VITE_CONTRACT_ADDRESS: 'bad' }, { VITE_CHAIN_ID: '41234' }, { VITE_PUBLIC_BASE_URL: 'https://localhost' }, { VITE_STALE_AFTER_MINUTES: 'NaN' }]) check(`invalid env ${JSON.stringify(env)}`, () => assert.throws(() => parseEnv(env)));
const record: TransactionRecord = { id: 'test', operation: 'health_check', stage: 'awaiting_signature', status: 'pending', startTime: 1, finalized: false };
check('record at start', () => assert.deepEqual(historyReducer([], { type: 'start', record }), [record]));
check('immutable update', () => { Object.freeze(record); const next = historyReducer([record], { type: 'patch', id: 'test', patch: { status: 'accepted' } }); assert.equal(record.status, 'pending'); assert.equal(next[0].status, 'accepted'); });
const hash = `0x${'1'.repeat(64)}`;
let reads = 0;
const accepted = await pollUntilAccepted({ getTransaction: async () => ++reads === 1 ? { statusName: 'PENDING', txExecutionResultName: 'NOT_VOTED' } : { statusName: 'ACCEPTED', txExecutionResultName: 'FINISHED_WITH_RETURN' } }, hash, undefined, undefined, { interval: 1, timeout: 50 });
check('pending then accepted', () => { assert.equal(accepted.kind, 'accepted-return'); assert.equal(reads, 2); });
const unknown = await pollUntilAccepted({ getTransaction: async () => ({ statusName: 'PENDING' }) }, hash, undefined, undefined, { interval: 1, timeout: 5 });
check('poll deadline unknown', () => assert.equal(unknown.kind, 'unknown'));
const final = await pollUntilFinalized({ getTransaction: async () => ({ statusName: 'FINALIZED', txExecutionResultName: 'FINISHED_WITH_RETURN' }) }, hash, () => {}, new AbortController().signal);
check('actual finality', () => assert.equal(final.statusName, 'FINALIZED'));
function files(dir: string): string[] { return readdirSync(dir, { withFileTypes: true }).flatMap(e => e.isDirectory() ? files(join(dir, e.name)) : [join(dir, e.name)]); }
check('source-wrapper guard', () => { for (const path of [...files(join(process.cwd(), 'src')), ...files(join(process.cwd(), 'scripts'))]) assert.doesNotMatch(readFileSync(path, 'utf8'), /\.contract\s*\(|contract\.(?:read|write)/); });
console.log(`OFFLINE ASSERTIONS: ${checks} passed. Synthetic fixtures only, not Vitest or Bradbury evidence.`);
